### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Add a background to the body element on the screen 
- [x] Add a div to the HTML to hold your car 
- [x] Style your car with CSS
