### ISSUE TITLE
User can turn their car 

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a data model to to hold which way the car is facing. 
- [x] Create CSS classes to make the car face different directions. 
- [x] Add an event listener for the keydown events on the window. 
- [x] Make an event handler function that rotates the car depending on which arrow button is pressed. 
- [x] Test the functionality 
- [x] Fix all errors
