### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x]  Change the car's positioning to absolute so it can move across the screen. 
- [x] Use the style property of element objects to change your car's top and left box offset styles.
- [x] Add a location to your data model to hold the x & y coordinates of your car's position on the page 
- [x] Add an event listener for pressing down the space key to start your car 
- [x] Create a function to move your car forward (change it's x coordinates)
- [x] use setInterval to move your car forward every 16ms after the user presses the space key
