### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Add a Boolean to your data model to indicate if the car has been started 
- [x] Update your function to include the Boolean and update its value every time the spacebar is pressed
- [x] Update your functions to stop the setInterval function when the spacebar is clicked to stop the car
