### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by tghaffari** [tghaffari/driving-game#5]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [ ] Make a new function for each keypress that changes the direction that the car is moving in 
- [x] Make a function for pressing down by increasing the value of the top property. (use data.y)
- [x] Make a function for pressing left by decreasing the value of the left property (use data.x)
- [ ] make a function for pressing up by decreasing the value of the top property. (use data.y)
- [ ] Test out functionality 
- [ ] Fix errors
